#
#
#
#
#

include Makefile.conf

all:
	cd ready && $(MAKE)

install:
	cd ready && $(MAKE) install

install-viz:
	cd viz && $(MAKE) install

rpminstall-viz:
	cd viz && $(MAKE) rpminstall

clean:
	cd ready && $(MAKE) clean
